### ISSUE TITLE
Body sliders cosmetic fix

### ISSUE THREAD

**Issue by linkanon** [aa2g/AA2Unlimited#19]
It's a small change but it modifies the AAUnlimitedDll.rc which is also edited in the [PR#18](https://github.com/aa2g/AA2Unlimited/pull/18). Basically, I suggest resizing the sliders so that they fill the whole horizontal space. On my end I resized the sliders dialogue window and the slider within but there may be a better way that will dynamically fill all the available space.
Here's a pic for reference: 
![Body Sliders tab example](https://cloud.githubusercontent.com/assets/13915973/21123571/78dabf56-c0a7-11e6-9087-690fffc6e83f.png)

**Comment by AA2Hackanon** [comment]
The window itself can't be scaled, so i don't think dynamic scaling would be necessary.
The empty space was there cause i originally intended to have 2 columns, but i ended up scrapping that idea when i did the sliders dynamically where the ordering would be kinda annoying to define. Resizing them to fill the space definitely makes sense.

**Comment by linkanon** [comment]
Sounds good. Figured that's a leftover from the two-column times.
Semi-related but is there a way to change the size of the slider steps when you press up/down? Right now each keypress adds an unnoticeable amount so making steps around 0.001 would be enough.

**Comment by AA2Hackanon** [comment]
doable by sending TBM_SETLINESIZE/SETPAGESIZE messages, probably where they are created inside the BodySlider constructor. Making the step 0.001 for all of them sounds a little counter-intuitive though, as different step sizes can have different effects on different sliders.
Maybe an increase by x% of the slider range would make more sense

**Comment by linkanon** [comment]
Yeah, I got the 0.001 value from the total body width slider and it will definitely act wrong for others. Range percentage makes more sense. 

One more thing: how often do you check aa2g? [This anon](https://boards.4chan.org/vg/thread/162353557#p162598070) found two crashes I never knew of so I'm thinking of organizing some kind of bug tracker or a single Issue with a list of crashes because making an issue for each crash is excessive imo.

**Comment by AA2Hackanon** [comment]
I usually visit aa2g once or twice a day and read up on all the posts since last time. Most of the bugs i know about, i actually know about because someone posted it on there, since i rarely come around actually playing the game anymore.
The body sliders were pretty unstable in general. The pure existence of bone sliders specifically would cause a crash pretty much every time the model was reloaded (e.g changing clothes or body height) and had additional issues (e.g changing the body between slim/normal/fat reordered them for some reason), so i hope that bug that anon mentioned was fixed with the last slider commit.
Frame sliders we're unstable in a similar manner a while ago, which might be his problem as well. Would cause a crash when switching to this tab as well. Not sure how old his version is.
About the skip H scene, i don't know what he means with that.

Bug tracker might be a good idea, though im not sure how to do something like that. Having a "general bug issue" would be kind of defeating the point of issues though, not to mention that you need a github account to report a bug.

**Comment by linkanon** [comment]
Just checked: both crashes are still present. 
the `skip H scene` crash happens when you enter H with this feature turned on in the game's settings 3rd tab(it just dims the screen instead of going to the sex). Might be related to either the hAI or the POV. 

If you check aa2g that often then the issues tab would be enough, I thought you do it like twice a week.
